- lib/connectors/connector.js
- lib/connectors/ftp.js
- lib/connectors/sftp.js
- lib/views/directory-view.js
Directory structure is now created in the correct order. Promises are now chained.
> Fixed errors on creating recursive directory structure

- lib/config/server-schema.json
- lib/ftp-remote-edit.js
- lib/views/configuration-view.js
- lib/views/directory-view.js
- lib/views/file-view.js
- styles/ftp-remote-edit.less
Added setting to define initial directory.
Solved Issues:
[Feature Request] Initial directory #9
> Added setting to define initial directory.

- lib/config/server-schema.json
- lib/connectors/sftp.js
- lib/views/configuration-view.js
- lib/views/directory-view.js
Added Option to define path for ssh/sftp private keyfile.
> [Feature Request] Connect using a private key #6

- styles/ftp-remote-edit.less
Solved Issue: Styles for light theme #17
> Fixed styles for light theme

- keymaps/keymap.cson
Added a single hotkey for toggling ftp-remote-edit, currently ctrl-space.
https://github.com/h3imdall/ftp-remote-edit/issues/37
> Adds hotkey for toggling

- lib/views/configuration-view.js
Hide password in server settings #36
> Mask input for password.

- lib/connectors/connector.js
- lib/connectors/sftp.js
- lib/views/file-view.js
- package.json
Update dependencies of ssh2-sftp-client from 1.0.5 to 1.1.0 and changed tranfermode for files from utf8 to to binary.
Solves issue Image view doesn't work #58
> Image view doesn't work #58

- lib/connectors/connector.js
- lib/views/file-view.js
Added function to check if a file is already open. Changed order how files are downloaded and opened.
Solves issue Image view doesn't work #62
> Undo just opened file #62

- lib/ftp-remote-edit.js
Solve issue Uncaught SyntaxError: Unexpected token  in JSON at position 0 #44
when new master password is required with existing config
> Check that password from new master password can decrypt current config

- lib/ftp-remote-edit.js
Try to fix issue #173 checking that editor.getPath() does not return a null string
> Checked that editor.getPath() returns a not null String

- lib/config/server-schema.json
- lib/connectors/connector.js
- lib/connectors/sftp.js
- lib/views/configuration-view.js
- styles/ftp-remote-edit.less
Doesn't support unlocking of keyfiles yet, but falls back gracefully if you provide the relevant information.
> Add suppport for agent based authentication

- lib/views/directory-view.js
Sorting on views ignoring upper/lower case characters.
> Natural sorting

- lib/config/server-schema.json
- lib/ftp-remote-edit.js
- lib/views/server-view.js
- menus/ftp-remote-edit.json
- package.json
I found out that great would be allowing adding temporary server to config. So i've done such change ;)
> Handleuri addtoconfig

- lib/ftp-remote-edit.js
- menus/ftp-remote-edit.json
I've needed sometimes to download file to other location than opening in atom (for example graphics). I've added possibility for open dialog to ask user where to save a file.
> Allow to download file from context menu

- lib/helper/import.js
- lib/helper/storage.js
- lib/views/configuration-view.js
- package.json
Regarding to #49 , first try.
I don't like sending object of ConfigurationView to Import, but i don't know to reload it otherwise.
Fell free to give review ;)
> Allowing to import connections from filezilla

- lib/ftp-remote-edit.js
- lib/views/tree-view.js
I found out that when we have 3 temp servers added, and run 'add to config' on one of them - other are deleted from tree view.
> Small correction for temp servers - keep them after adding one to config

- lib/config/config-schema.json
- lib/ftp-remote-edit.js
Selected download folder, or upload on desktop could not always be a great idea. So, i've added possibility to provide one for each in config file.
> Allow to select default path for download, and upload

- lib/dialogs/prompt-pass-dialog.js
- lib/ftp-remote-edit.js
- lib/helper/storage.js
- lib/views/configuration-view.js
- lib/views/server-view.js
For some servers we don't want even to save encrypted password, so added possibility to select 'prompt for password' on servers.
> Allow to select prompt for password on servers

- lib/connectors/connector.js
- lib/connectors/ftp.js
- lib/connectors/sftp.js
- lib/ftp-remote-edit.js
- lib/helper/queue.js
- lib/helper/storage.js
- lib/views/directory-view.js
- lib/views/file-view.js
- lib/views/folder-view.js
- lib/views/server-view.js
> 减少或者消除 puslar使用过程中的报错和提示

- package.json
This fixed bug All configured authentication methods failed with ssh key #431
> Fix SSH2 bug
